#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "kutuphane.h"
int main(){
	Figure *fig_fx=(Figure*)malloc(sizeof(Figure));
	Color c;
	c.red=0;
	c.green=0;
	c.blue=0;
	Point2D *poly_line=(Point2D*)malloc(30*sizeof(Point2D));
	poly_line[0].x=-100;
	poly_line[0].y=260;
	poly_line[1].x=100;
	poly_line[1].y=260;
	poly_line[2].x=220;
	poly_line[2].y=100;
	poly_line[3].x=220;
	poly_line[3].y=-100;
	poly_line[4].x=100;
	poly_line[4].y=-260;
	poly_line[5].x=-100;
	poly_line[5].y=-260;
	poly_line[6].x=-220;
	poly_line[6].y=-100;
	poly_line[7].x=-220;
	poly_line[7].y=100;
	poly_line[8].x=-100;
	poly_line[8].y=260;
	fig_fx=start_figure(1000,1000);
	set_thickness_resolution(fig_fx,1,1);
	set_color(fig_fx,c);
	draw_fx(fig_fx,f,-40,40,0.1);
	export_eps(fig_fx,"Fx.eps");
	Point2D start_roi, end_roi;
	start_roi.x=-750;
	start_roi.y=-750;
	end_roi.x=750;
	end_roi.y=750;
	c.red=1;
	Figure *fig_polyline=(Figure*)malloc(sizeof(Figure));
	fig_polyline=start_figure(1000,1000);
	set_thickness_resolution(fig_polyline,5,1);
	set_color(fig_polyline,c);
	draw_polyline(fig_polyline,poly_line,5);
	export_eps(fig_polyline,"Polyline.eps");
	c.red=0;
	c.blue=1;
	Point2D *centre=(Point2D*)malloc(sizeof(Point2D));
	Point2D *width_height=(Point2D*)malloc(sizeof(Point2D));
	centre->x=0.0;
	centre->y=0.0;
	width_height->x=700;
	width_height->y=300;
	Figure *fig_polygon=(Figure*)malloc(sizeof(Figure));
	fig_polygon=start_figure(1000,1000);
	set_thickness_resolution(fig_polygon,5,1);
	set_color(fig_polygon,c);
	draw_polygon(fig_polygon,poly_line);
	export_eps(fig_polygon,"Polygon.eps");
	Figure *fig_ellipse=(Figure*)malloc(sizeof(Figure));
	fig_ellipse=start_figure(1000,1000);
	set_thickness_resolution(fig_ellipse,1,5);
	c.green=1;
	set_color(fig_ellipse,c);
	draw_ellipse(fig_ellipse,centre,width_height);
	export_eps(fig_ellipse,"Ellipse.eps");
	Figure *fig_append,*fig_append2,*fig_resize,*fig_scale,*fig_scale2,*fig_resize2;
	scale_figure(fig_ellipse,2,2);
	export_eps(fig_ellipse,"Scale_Ellipse.eps");
	start_roi.x=-1000;
	start_roi.y=-1000;
	end_roi.x=1000;
	end_roi.y=1000;	
	resize_figure(fig_ellipse,&start_roi,&end_roi);
	export_eps(fig_ellipse,"Resize_Scale_Ellipse.eps");
	resize_figure(fig_polygon,&start_roi,&end_roi);
	export_eps(fig_polygon,"Resize_Polygon.eps");
	append_figures(fig_polygon,fig_ellipse);
	export_eps(fig_polygon,"Append_Resize_Polygon_Ellipse.eps");
	scale_figure(fig_fx,3,3);
	export_eps(fig_fx,"Scale_fx");
	append_figures(fig_polyline,fig_fx);
	export_eps(fig_polyline,"Append_Polyline_Fx.eps");
	start_roi.x=-100;
	start_roi.y=-100;
	end_roi.x=100;
	end_roi.y=100;
	resize_figure(fig_fx,&start_roi,&end_roi);
	export_eps(fig_fx,"Resize_Scale_Fx.eps");
}